wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name='wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>",views.entry_page,name="entry"),
    path("search",views.search,name="search"),
    path("random",views.random_page,name="random"),
    path("edit/<str:title>",views.edit_page,name="edit"),
    path("create",views.new_page,name="create")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import markdown2, random
from django.contrib import messages

from . import util

#display list of entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

#convert markdown to html and display entries
def entry_page(request,title):
    entry_content = util.get_entry(title)
    return render(request,"encyclopedia/entry.html",{
                "title": title,
                "value":markdown2.markdown(entry_content) if entry_content else None
    })

#use for search
def search(request):
    entries = util.list_entries()
    query = request.GET.get("q", "")
    for i in entries:
        if i.lower() == query.lower():
            return redirect('wiki:entry', title=query)
        
    for i in entries:
        query_list = [entry for entry in entries if query.lower() in entry.lower() ]
        return render(request,"encyclopedia/search_result.html", {
            "entries": query_list
        })

#random page 
def random_page(request):
    entries = util.list_entries()
    choice = random.choice(entries)

    entry_content = util.get_entry(choice)
    return render(request,"encyclopedia/entry.html",{
        "title" : choice,
        "value": markdown2.markdown(entry_content)
    })

#edit Page
def edit_page(request,title):
    #when the data is submitted to form
    if request.method == "POST":
        content = request.POST.get('textbox','').replace('\r\n','\n').strip() # to remove extra line space we added replace('\r\n', '\n')
        if content:
            util.save_entry(title,content)
            return redirect('wiki:entry',title)


    else:
        #when the edit button is clicked and data is not submitted to form GET Request 
        content = util.get_entry(title)
        return render(request,"encyclopedia/edit.html",{
        "title":title,
        "value": content #no need to convert to html here because this section is for user to edit in markdown format
        })


#new page
def new_page(request):
    if request.method =="POST":
        title = request.POST.get('title_box','').strip()
        content = request.POST.get('blog_box','').strip()

        # # Check if title is empty or already exists
        
        # if not title:  #used require html to eliminate this
        #     messages.error(request, "Title cannot be empty.")
        #     return render(request, 'encyclopedia/new_page.html')

        if title.lower() in [i.lower() for i in util.list_entries()]:
            messages.error(request, f"An entry with the title '{title}' already exists.")
            return render(request, 'encyclopedia/new_page.html')


        # Save the entry
        util.save_entry(title, content)
        messages.success(request, f"The page '{title}' has been successfully created.")
        return redirect('wiki:entry', title=title)


    else:
        return render(request,'encyclopedia/new_page.html')

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}


{% block body %}
    <form action="{% url 'wiki:edit' title %}" method="POST">
        {% csrf_token %}
        <textarea style="resize:none; width: 75vw;" class="textbox_edit" name="textbox" autocomplete="on" spellcheck="True" required>{{value}}</textarea>
        <div>
            <input class="btn btn-success mt-2" type="submit" value="submit">
        </div>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <a role="button" class="btn btn-primary" href="{% url 'wiki:edit' title%}">Edit Page</a>

    {% if value%}
        <p>{{value|safe}}</p>
    {% else %}
        <h1>Entry Not Found</h1>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{entry}}</a></li> 
            <!-- 2nd entry is the argument first entry is the route for entry, this name was given in url.py -->
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <img src="https://en.wikipedia.org/static/images/icons/wikipedia.png" width="120px">
                <h2>Wiki-pedia</h2>
                <form action="{% url 'wiki:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="{%url 'wiki:random'%}">Random Page</a>                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <form action="{% url 'wiki:create' %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="title"><h3>Enter Title: &nbsp;</h3></label>
            <input style="width:400px" id="title" type="text" name="title_box" placeholder="Enter Title" required>
        </div>

        <div>
            <div class="message">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}        
            </div>
        
            <label for="blog"><h3>Enter content:</h3></label>
            <br>
            <textarea style="resize:none; width: 75vw; height: 75vh;" id="blog"  autocomplete="on" placeholder="Enter content" spellcheck="true" name="blog_box" ></textarea>
    
        </div>
        
        <div>
        <input class="btn btn-success mt-2 " type="submit" value="submit">
        </div>
    </form>
{% endblock %} 

wiki/encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html " %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}

    <h1>Search Results</h1>

    {% if entries %}
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'wiki:entry' entry %}">{{entry}}</a></li>
            {% endfor %}
        </ul>

    {%else%}
        <br>
        <h3>Query didnt match any item, Please try again or create a  <a href="{% url 'wiki:create' %}">new entry</a></h3>
    {% endif %}

{% endblock %}